# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
      with:
        enable-cache: true
    - name: Sync dependencies
      run: rye sync
    - name: Get release tag
      id: get_tag
      run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Write version to _version.py
      run: |
        python -m pip install --upgrade pip
        pip install hatch
        hatch version ${RELEASE_TAG}

    - name: Build package
      run: rye build
    - name: publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
          password: ${{ secrets.PYPI_API_TOKEN }}
